version: '3.7'

services:
  redis:
    image: redis:5.0.5
    container_name: marvel_redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_DOCKER: redis:6379
    depends_on:
      - redis
    ports:
      - "9091:9091"