definitions:
  model.Character:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  model.HTTPError400:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  model.HTTPError404:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: Not Found
        type: string
    type: object
  model.HTTPError500:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Internal Server Error
        type: string
    type: object
info:
  contact:
    email: ahmad.hassan@gmail.com
    name: Dr Ahmad Hassan
    url: https://www.linkedin.com/in/ahmadhassan
  description: This is an api for querying the Marvel characters.
  termsOfService: http://swagger.io/terms/
  title: Marvel Characters API
  version: "1.0"
paths:
  /characters:
    get:
      consumes:
      - application/json
      description: Returns the IDs of all the Marvel Characters.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
              example: 1010674
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError500'
      summary: Serves an endpoint /characters that returns all the Marvel character
        ids in a JSON array of numbers.
      tags:
      - Characters
  /characters/{characterId}:
    get:
      consumes:
      - application/json
      description: Serve an endpoint /characters/{characterId} that returns only the
        id, name and description of the character.
      parameters:
      - description: ID of the character
        in: path
        name: characterId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Character'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HTTPError400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError500'
      summary: Gets the details of a particular Marvel character
      tags:
      - Characters
swagger: "2.0"
